---
title: "Model Testing - BART"
author: "ernestsalim"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidymodels)
library(tidyverse)
library(dbarts)
```

```{r}
train <- read_csv("train_25.csv")
test <- read_csv("test.csv")
```

```{r}
train %>% head()
```

```{r}
folds <- vfold_cv(train, v = 3, strata = percent_dem)
```

```{r}
model <- parsnip::bart(
    # trees = tune(),
    # prior_terminal_node_coef = tune(),
    # prior_terminal_node_expo = tune()
    trees = 1000,
    prior_terminal_node_coef = 0.978036853,
    prior_terminal_node_expo = 2.286887
  ) %>%
  set_engine("dbarts") %>%
  set_mode("regression")

recipe <- recipe(percent_dem ~ ., data = train) %>% 
  step_impute_mean(all_numeric_predictors()) %>% 
  step_mutate(x2013_code = factor(x2013_code)) %>% 
  step_corr(all_numeric_predictors(), threshold = 0.999) %>% 
  step_nzv(all_numeric_predictors()) %>% 
  step_log(all_numeric_predictors(), offset = 1) %>%
  step_normalize(all_numeric_predictors()) %>%
  step_dummy(all_nominal())

workflow <- workflow() %>% 
  add_recipe(recipe) %>% 
  add_model(model)
```

```{r}
# Without Tuning
fit <- workflow %>% 
  fit_resamples(resamples = folds)
show_notes(.Last.tune.result)
```

```{r}
# Random Tuning Grid
set.seed(214)
grid <- grid_random(parameters(model), size = 30)

fit <- workflow %>% 
  tune_grid(resamples = folds,
            grid = grid,
            control = control_grid(verbose = TRUE))
show_notes(.Last.tune.result)
```

```{r}
fit %>% collect_metrics() %>% arrange(mean) %>% filter(.metric == "rmse")
```

```{r}
trained_workflow <- workflow %>%
  fit(train)
```

```{r}
pred <- test %>% 
  select(id) %>% 
  bind_cols(trained_workflow %>% predict(new_data = test))
```

```{r}
pred %>% head()
```

```{r}
write_csv(pred, file = "pred.csv")
```






