---
title: "Model Testing - LightGBM"
author: "ernestsalim"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidymodels)
library(tidyverse)
library(recipes)
library(dials)
library(tune)

library(bonsai)
library(lightgbm)
```

```{r}
train <- read_csv("train_25.csv")
test <- read_csv("test.csv")
```

```{r}
train %>% head()
```

```{r}
# train[train == 0] <- NA
# test[test == 0] <- NA
folds <- vfold_cv(train, v = 2, strata = percent_dem)
```

```{r}
spec <- boost_tree(
      trees = tune(),
      min_n = tune(),
      tree_depth = tune(),
      learn_rate = tune()
      # trees = 888,
      # min_n = 39,
      # tree_depth = 12,
      # learn_rate = 0.09854
  ) %>% 
  set_engine("lightgbm") %>% 
  set_mode("regression")

rec <- recipe(percent_dem ~ ., data = train) %>% 
  step_rm(c01_025e, c01_019e, c01_016e, x0033e) %>% 
  step_mutate(x2013_code = factor(x2013_code)) %>% 
  step_impute_mean(all_numeric_predictors()) %>% 
  step_zv(all_numeric_predictors()) %>% 
  # step_log(all_numeric_predictors()) %>% 
  step_YeoJohnson(all_numeric_predictors()) %>% 
  step_normalize(all_numeric_predictors()) %>% 
  step_dummy(all_nominal())

workflow <- workflow() %>% 
  add_recipe(rec) %>% 
  add_model(spec)
```

```{r}
# Without Tuning
fit <- workflow %>% 
  fit_resamples(resamples = folds, control = control_grid(verbose = TRUE))
show_notes(.Last.tune.result)
```

```{r}
fit %>% collect_metrics()
```

```{r}
fitted_workflow <- workflow %>% fit(train)
```

```{r}
pred <- fitted_workflow %>% predict(new_data = test)
```

```{r}
pred <- test %>% 
  select(id) %>% 
  bind_cols(pred)
```

```{r}
write_csv(pred, "pred.csv")
```

---

```{r}
# Random Tuning Grid
set.seed(214)
grid <- grid_random(parameters(spec), size = 20)

fit <- workflow %>% 
  tune_grid(resamples = folds,
            grid = grid,
            control = control_grid(verbose = TRUE))
show_notes(.Last.tune.result)
```

```{r}
fit %>% collect_metrics()
```

```{r}
best_params <- fit %>%
  select_best(metric = "rmse") 

best_workflow <- workflow %>% 
  finalize_workflow(best_params)

best_workflow
```

```{r}
fitted_workflow <- best_workflow %>% fit(train)
pred <- fitted_workflow %>% predict(new_data = test)
```

```{r}
pred <- test %>% 
  select(id) %>% 
  bind_cols(pred)
write_csv(pred, "pred.csv")
```

```{r}
pred
```










